config/routes.rb
Rails.application.routes.draw do


  root to: "homes#top"
  get 'home/about' => "homes#about"
  devise_for :users

  resources :books, only: [:create, :destroy, :show, :index, :edit, :update]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: {in: 2..20}, uniqueness: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :introduction, length: {maximum: 50}


  def get_profile_image(width, height)
      unless profile_image.attached?
        file_path=Rails.root.join('app/assets/images/default.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
      end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :correct_user, only: [:edit, :update]

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      @user=User.find_by(id: current_user.id)
      render :index
    end
  end

  def index
    @user=User.find_by(id: current_user.id)
    @book=Book.new
    @books=Book.all
  end

  def show
    @book=Book.find(params[:id])
    @user=@book.user
    @new_book=Book.new
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end


  def correct_user
    @book=Book.find(params[:id])
    @user=@book.user
    redirect_to books_path unless @user==current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
    if @user==current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to  user_path(@user)
    else
      render :edit
    end
  end

  def index
    @user=User.find_by(id: current_user.id)
    @book=Book.new
    @users=User.all
  end

  private
  def user_params
     params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to user_path(current_user) unless @user==current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_side.html.erb
<div class="container">
  <h2 class="text-left">User info</h2>
  <div class="row ml-1">
  <%= image_tag user.get_profile_image(100,100) %>
  </div>
<table class="table">
  <tr>
    <th style="width: 50%">name</th>
    <th style="width: 50%"><%= user.name %></th>
  </tr>
  <tr>
    <th style="width: 50%">introduction</th>
    <th style="width: 50%"><%= user.introduction %></th>
  </tr>
</table>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>

</div>

<div class="container mt-5">
  <h2>New book</h2>
  <%= form_with model: book, url: books_path do |f| %>
  <div class="row ml-1 mr-1">
    <label>Title</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_field :title, class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1">
    <label>Opinion</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_area :body, class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1">
    <%= f.submit "Create Book", class: "btn btn-success btn-sm text-light" %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container-sm mt-3 w-75">
  <h2>Editing Book</h2>
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @book do |f| %>
  <div class="row ml-1 mr-1">
    <label>Title</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_field :title, class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1">
    <label>Opinion</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_area :body, class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1 mb-4">
    <%= f.submit "Update Book", class: "btn btn-success btn-sm" %>
  </div>
  <% end %>
  <div class="row ml-1 mr-1">
    <%= link_to "Show", book_path(@book), class: "mr-1" %> | <%= link_to "Back", books_path, class: "ml-1" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container w-100 mt-3 pl-4 pr-4">
 <% if @book.errors.any? %>
  <h3 class="ml-5"><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
   <ul class="ml-5">
     <% @book.errors.full_messages.each do |message| %>
       <li><%=  message %></li>
     <% end %>
   </ul>
 <% end %>
  <div class="row justify-content-around">
    <div class="col-12 col-md-3 mb-5">
      <%= render 'side', user: @user, book: @book %>
    </div>
    <div class="col-10 col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <th>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </th>
          <th>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </th>
          <th><%= book.body %></th>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container w-100 mt-3 pl-4 pr-4">
  <div class="row justify-content-around">
    <div class="col-12 col-md-3 mb-5">
      <%= render 'books/side', user: @user, book: @new_book %>
    </div>
    <div class="col-10 col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@book.user.id) do %>
              <%= image_tag @book.user.get_profile_image(80,80) %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user==current_user %>
          <td>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm" %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete, "data_confirm"=>"本当に消しますか？", class: "btn btn-danger btn-sm" %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1 class="text-center mt-3">Welcome to <span><strong><i class="fas fa-book"></i>Bookers</strong></span>!</h1>

app/views/homes/top.html.erb
<div class="container pt-4">
  <div class="row">
    <div class="col-md-6 col-sm-10 m-auto">
      <h1>welcome to <span><strong><i class="fas fa-book"></i>Bookers</strong></span> !!</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-10 m-auto">
      <p style="line-height:2.5rem">
        In <strong><i class="fas fa-book"></i>Bookers</strong>,<br>
        you can share and exchange your opinions, inpressions, and emotions<br>
        about various books!
      </p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row p-2">
    <div class="col-md-5 col-8 m-auto">
      <%= link_to "Log in", new_user_session_path, class: "btn-info btn-block btn-sm text-light text-decoration-none text-center" %>
    </div>
  </div>
  <div class="row p-2">
    <div class="col-md-5 col-8 m-auto">
      <%= link_to "Sign up", new_user_registration_path, class: "btn-success btn-block btn-sm text-light text-decoration-none text-center" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/f13f46161f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to home_about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div>
        <% if flash[:notice] %>
          <p id="notice">
            <%= flash[:notice] %>
          </p>
        <% end %>
      </div>
      <%= yield %>
    </main>

    <footer class="text-center p-5">
      <p>CopyRight Infratop.inc</p>
    </footer>


  </body>
</html>

app/views/users/edit.html.erb
<div class="container-sm mt-3 w-75">
  <h2>User info</h2>
  <% if @user.errors.any? %>
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @user do |f| %>
  <div class="row ml-1 mr-1">
    <label>Name</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_field :name, autofocus: true, placeholder: "#{current_user.name}", class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1">
    <label>Image</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %>
  </div>
  <div class="row ml-1 mr-1">
    <label>Introduction</label>
  </div>
  <div class="row mb-3 ml-1 mr-1">
    <%= f.text_area :introduction, class: "w-100" %>
  </div>
  <div class="row ml-1 mr-1">
    <%= f.submit "Update User", class: "btn btn-secondary btn-sm" %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container w-100 mt-3 pl-4 pr-4">
  <div class="row justify-content-around">
    <div class="col-12 col-md-3 mb-5">
      <%= render 'books/side', user: @user, book: @book %>
    </div>
    <div class="col-10 col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <th>
            <%= image_tag user.get_profile_image(80,80) %>
          </th>
          <th>
            <%= user.name %>
          </th>
          <th>
            <%= link_to "Show", user_path(user.id) %>
          </th>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container w-100 mt-3 pl-4 pr-4">
  <div class="row justify-content-around">
    <div class="col-12 col-md-3 mb-5">
      <%= render 'books/side', user: @user, book: @book %>
    </div>
    <div class="col-10 col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>